import { AlertCircle, Inbox, LoaderCircle } from 'lucide-react'
import type { ReactNode } from 'react'
import { Button } from '@/components/ui'

export function AdminPage({ eyebrow = '管理后台', title, description, action, children }: { eyebrow?: string; title: string; description: string; action?: ReactNode; children: ReactNode }) {
  return <main className="app-page h-full overflow-y-auto"><div className="mx-auto w-full max-w-[1480px]"><header className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="app-eyebrow">{eyebrow}</p><h1 className="app-page-title mt-1">{title}</h1><p className="app-page-description mt-1.5">{description}</p></div>{action && <div className="flex shrink-0 flex-wrap items-center gap-2">{action}</div>}</header>{children}</div></main>
}

export function LoadingState({ label = '正在加载' }: { label?: string }) { return <div className="app-panel grid min-h-44 place-items-center text-sm text-slate-500"><span className="flex items-center gap-2"><LoaderCircle className="size-4 animate-spin" />{label}</span></div> }
export function ErrorState({ onRetry }: { onRetry: () => void }) { return <div role="alert" className="grid min-h-44 place-items-center rounded-[var(--radius-panel)] border border-red-200 bg-red-50 p-6 text-center"><div><AlertCircle className="mx-auto mb-2 size-6 text-red-600" /><p className="font-medium text-red-900">数据加载失败</p><p className="mt-1 text-sm text-red-700">请检查网络后重试。</p><Button className="mt-4" size="sm" variant="secondary" onClick={onRetry}>重新加载</Button></div></div> }
export function EmptyState({ title = '暂无数据', description = '调整筛选条件后再试。' }: { title?: string; description?: string }) { return <div className="grid min-h-44 place-items-center rounded-[var(--radius-panel)] border border-dashed border-slate-300 bg-white p-6 text-center"><div><Inbox className="mx-auto mb-2 size-6 text-slate-400" /><p className="font-medium text-slate-800">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div></div> }
export function StatusBadge({ active, activeText = '正常', inactiveText = '停用' }: { active: boolean; activeText?: string; inactiveText?: string }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 text-xs font-medium ${active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}><span className={`size-1.5 rounded-full ${active ? 'bg-emerald-600' : 'bg-slate-400'}`} aria-hidden />{active ? activeText : inactiveText}</span> }
export function messageOf(error: unknown) { return error instanceof Error ? error.message : '操作失败，请稍后重试。' }
export function formatDate(value?: string | null) { if (!value) return '—'; const date = new Date(value.includes('T') ? value : `${value.replace(' ', 'T')}Z`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(date) }
