name = "hpc-cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"

[observability]
enabled = true

[[routes]]
pattern = "hpc.email"
custom_domain = true

[[d1_databases]]
binding = "db"
database_name = "hpc-cloud-mail-db"
database_id = "4888de56-5d04-4ccf-b0ab-44d309306d23"

[[kv_namespaces]]
binding = "kv"
id = "740790d8a32f4286833f17940358f1bb"

[[r2_buckets]]
binding = "r2"
bucket_name = "hpc-cloud-mail-r2"

[[send_email]]
name = "email"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
analysis_cache = false
domain = ["hpc.email", "happyclaw.cc", "riba2534.cn", "tiktok-row.cn", "option.red", "claude-router.cc"]
admin = "admin@hpc.email"
project_link = false

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
